import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../components/Nav/Nav'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>AGÁ Empreendimentos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </>
  )
}

export default Home