import type { NextPage } from 'next'
import Head from 'next/head'

import 'tw-elements';

import { Company } from '../components/Company'
import { Acordion } from '../components/Acordion'
import { Header } from '../components/Header'
import { About } from '../components/About'
import Policy from '../components/Policy'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>AGÁ Empreendimentos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Policy />
      <Header />
      <About />
      <Company />
      <Acordion />
    </>
  )
  
}

export default Home